### ISSUE TITLE
Beta view - Graph view in Feed list not working

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1110]
Selecting a single feed and then click on 'graph View' gives the following message

![image](https://user-images.githubusercontent.com/1322749/48302956-b76b8000-e4fb-11e8-9e14-4594ba98c2f5.png)

<details><summary>Server Information</summary>

| | | |
| --- | --- | --- |
|Emoncms|Version|9.9.3
||Modules|Administration : App v1.1.1 : Backup v1.1.4 : Dashboard v1.3.0 : Device v1.1.0 : EventProcesses : Feed : Input : CoreProcess : Schedule : Time : User : Visualisation
||Git URL|https://github.com/emoncms/emoncms.git
||Git Branch|* master
|Server|OS|Linux 4.9.0-6-amd64
||Host|DietPi-EmoncmsVM DietPi-EmoncmsVM (192.168.7.47)
||Date|2018-11-10 15:22:39 UTC
||Uptime| 15:22:39 up 25 days, 20:38,  0 users,  load average: 0.00, 0.00, 0.00
|HTTP|Server|lighttpd/1.4.45 HTTP/1.1 CGI/1.1 80
|MySQL|Version|5.5.5-10.1.26-MariaDB-0+deb9u1
||Host|localhost (127.0.0.1)
||Date|2018-11-10 15:22:39 (UTC 00:00‌​)
||Stats|Uptime: 1928025  Threads: 2  Questions: 2031325  Slow queries: 0  Opens: 41  Flush tables: 1  Open tables: 35  Queries per second avg: 1.053
|Redis|Version|3.2.6
||Host|localhost:6379 (127.0.0.1)
||Size|<span id="redisused">6032 keys  (1.78M)</span>
||Uptime|22 days
|MQTT Server|Version|Mosquitto 
||Host|192.168.7.50:1883 (192.168.7.50)
|Memory|RAM|Used: 32.51% Total: 492.5 MB Used: 160.11 MB Free: 332.4 MB
||Swap|Used: 0.00% Total: 1.52 GB Used: 0 B Free: 1.52 GB
|Disk|Mount|Stats
||/|Used: 38.56% Total: 7.81 GB Used: 3.01 GB Free: 4.7 GB
|PHP|Version|7.0.30-0+deb9u1 (Zend Version 3.0.0)
||Modules|apcu v5.1.8 : calendar v7.0.30-0+deb9u1 : cgi-fcgi : Core v7.0.30-0+deb9u1 : ctype v7.0.30-0+deb9u1 : curl v7.0.30-0+deb9u1 : date v7.0.30-0+deb9u1 : dom v20031129 : exif v7.0.30-0+deb9u1 : fileinfo v1.0.5 : filter v7.0.30-0+deb9u1 : ftp v7.0.30-0+deb9u1 : gd v7.0.30-0+deb9u1 : gettext v7.0.30-0+deb9u1 : hash v1.0 : iconv v7.0.30-0+deb9u1 : json v1.4.0 : libxml v7.0.30-0+deb9u1 : mbstring v7.0.30-0+deb9u1 : mcrypt v7.0.30-0+deb9u1 : mosquitto v0.4.0 : mysqli v7.0.30-0+deb9u1 : mysqlnd vmysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $ : openssl v7.0.30-0+deb9u1 : pcre v7.0.30-0+deb9u1 : PDO v7.0.30-0+deb9u1 : pdo_mysql v7.0.30-0+deb9u1 : Phar v2.0.2 : posix v7.0.30-0+deb9u1 : readline v7.0.30-0+deb9u1 : redis v3.1.6 : Reflection v7.0.30-0+deb9u1 : session v7.0.30-0+deb9u1 : shmop v7.0.30-0+deb9u1 : SimpleXML v7.0.30-0+deb9u1 : sockets v7.0.30-0+deb9u1 : SPL v7.0.30-0+deb9u1 : standard v7.0.30-0+deb9u1 : sysvmsg v7.0.30-0+deb9u1 : sysvsem v7.0.30-0+deb9u1 : sysvshm v7.0.30-0+deb9u1 : tokenizer v7.0.30-0+deb9u1 : wddx v7.0.30-0+deb9u1 : xml v7.0.30-0+deb9u1 : xmlreader v7.0.30-0+deb9u1 : xmlwriter v7.0.30-0+deb9u1 : xsl v7.0.30-0+deb9u1 : Zend OPcache v7.0.30-0+deb9u1 : zip v1.13.5 : zlib v7.0.30-0+deb9u1
</details>
<details><summary>Client Information</summary>

| | | |
| --- | --- | --- |
|HTTP|Browser|Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Vivaldi/2.1.1337.36
|Screen|Resolution|1920 x 1080
|Window|Size|1482 x 877
</details>

**Comment by borpin** [comment]
Ah, I did not know it was a dependency. Perhaps some additional text around the 'beta features' button or a text message 'Please install Graph Module'?

I'll check tonight.

**Comment by borpin** [comment]
So installing the graph view worked. Should it not have simply honored the old 'vis' instruction?

I have raised an issue as the 'stats' (mean etc) are missing.

**Comment by borpin** [comment]
Now I get this error in the dashboard that worked fine with the vis........

```
Fatal error: Uncaught Error: Call to a member function fetch_array() on boolean in /var/www/emoncms/Modules/graph/graph_model.php:95 Stack trace: 
#0 /var/www/emoncms/Modules/graph/widget/graph_widget.php(16): Graph->getall(1) 
#1 /var/www/emoncms/Modules/dashboard/Views/loadwidgets.php(44): require_once('/var/www/emoncm...') 
#2 /var/www/emoncms/Modules/dashboard/Views/loadwidgets.php(24): load_widget('Modules/graph/w...', 'graph') 
#3 /var/www/emoncms/Modules/dashboard/Views/dashboard_view.php(30): require_once('/var/www/emoncm...') 
#4 /var/www/emoncms/core.php(75): include('/var/www/emoncm...') 
#5 /var/www/emoncms/Modules/dashboard/dashboard_controller.php(46): view('Modules/dashboa...', Array) 
#6 /var/www/emoncms/core.php(64): dashboard_controller() 
#7 /var/www/emoncms/index.php(191): controller('dashboard') 
#8 {main} thrown in /var/www/emoncms/Modules/graph/graph_model.php on line 95
```
