### ISSUE TITLE
emoncms_mqtt exception on boot

### ISSUE THREAD

**Issue by borpin** [emoncms/emoncms#1295]
I am seeing this in `daemon.log` on boot
```
May 27 10:35:02 emonpi emoncms_mqtt[879]: PHP Fatal error:  Uncaught RedisException: Connection refused in /var/www/emoncms/scripts/services/emoncms_mqtt/emoncms_mqtt.php:78
May 27 10:35:02 emonpi emoncms_mqtt[879]: Stack trace:
May 27 10:35:02 emonpi emoncms_mqtt[879]: #0 /var/www/emoncms/scripts/services/emoncms_mqtt/emoncms_mqtt.php(78): Redis->connect('localhost', 6379)
May 27 10:35:02 emonpi emoncms_mqtt[879]: #1 {main}
May 27 10:35:02 emonpi emoncms_mqtt[879]:   thrown in /var/www/emoncms/scripts/services/emoncms_mqtt/emoncms_mqtt.php on line 78
May 27 10:35:02 emonpi emoncms_mqtt[879]: Fatal error: Uncaught RedisException: Connection refused in /var/www/emoncms/scripts/services/emoncms_mqtt/emoncms_mqtt.php:78
May 27 10:35:02 emonpi emoncms_mqtt[879]: Stack trace:
May 27 10:35:02 emonpi emoncms_mqtt[879]: #0 /var/www/emoncms/scripts/services/emoncms_mqtt/emoncms_mqtt.php(78): Redis->connect('localhost', 6379)
May 27 10:35:02 emonpi emoncms_mqtt[879]: #1 {main}
May 27 10:35:02 emonpi emoncms_mqtt[879]:   thrown in /var/www/emoncms/scripts/services/emoncms_mqtt/emoncms_mqtt.php on line 78
```
I think this service needs to be more robust.

**Comment by TrystanLea** [comment]
I will link this post to issue #1290
