### ISSUE TITLE
Admin->Update fails with error message as runService in admin_model is now private

### ISSUE THREAD

**Issue by bobbarnes1981** [emoncms/emoncms#1908]
Error from server:
```
<br />
<b>Fatal error</b>:  Uncaught Error: Call to private method Admin::runService() from context '' in /var/www/emoncms/Modules/admin/admin_controller.php:221
Stack trace:
#0 /var/www/emoncms/core.php(80): admin_controller()
#1 /var/www/emoncms/index.php(257): controller('admin')
#2 {main}
  thrown in <b>/var/www/emoncms/Modules/admin/admin_controller.php</b> on line <b>221</b><br />
```

**Comment by reedy** [comment]
Fixed by https://github.com/emoncms/emoncms/pull/1904

**Comment by bobbarnes1981** [comment]
Fixed by https://github.com/emoncms/emoncms/pull/1904
