### ISSUE TITLE
New inputs not being created by MQTT

### ISSUE THREAD

**Issue by glynhudson** [emoncms/emoncms#758]
## Setup

emonPi latest emonSD (Oct17) updated to latest Emoncms V9.8.25

## Issue

When a new input is created on MQTT e.g `emon/emontx3/power1` the input does not appear in emoncms. Existing feeds are still updating

## Workaround

Restart the emonPi: after a restart the new inputs appear in the input process list 

## Log debug

In `emoncms.log`:

```
2017-12-18 11:58:10.322|ERROR|phpmqtt_input.php|exception 'ErrorException' with message 'Undefined variable: id' in /var/www/emoncms/Modules/input/input_model.php:50
Stack trace:
#0 /var/www/emoncms/Modules/input/input_model.php(50): exceptions_error_handler(8, 'Undefined varia...', '/var/www/emoncm...', 50, Array)
#1 /var/www/emoncms/scripts/phpmqtt_input.php(256): Input->create_input(1, 'emontx3', 'power1')
#2 [internal function]: message(Object(Mosquitto\Message))
#3 /var/www/emoncms/scripts/phpmqtt_input.php(112): Mosquitto\Client->loop()
#4 {main}
```
Line 50 in `input_model.php` : https://github.com/emoncms/emoncms/blob/master/Modules/input/input_model.php#L50

Line 112 in `phpmqtt_input.php` https://github.com/emoncms/emoncms/blob/master/scripts/phpmqtt_input.php#L112

This is a new issue after the recent updates to `phpmqtt_input.php`

**Comment by glynhudson** [comment]
Fixed https://github.com/emoncms/emoncms/commit/1b0642a65ae78a7a145bbb56fe548e7d992201d6
