### ISSUE TITLE
Gaug and feedvalue not showing after update 9.8.3-->9.8.30

### ISSUE THREAD

**Issue by Rai-Rai** [emoncms/emoncms#862]
Hi,
I've just updated from version 9.8.3 to 9.8.30
Updating went smoothly everything looked ok.

But I can't see the Gaug, feedvalue, sun and cylinder widget on the dashboard if i'm not logged in (it works fine if I'm logged in)

In this case the browser console logs a lot of
```Review config for feed id of feedvalue
jgauge_render.js:48 Review config for feed id of jgauge
3feedvalue_render.js:253 Review config for feed id of feedvalue
```

Also (not sure if this is the same problem or an other one) in the browser network monitor I'm seeing the following error for requests goint to `feed/list.json?userid=1`:
```
Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in /var/www/vhosts/MY_SERVER/httpdocs/statistic/Modules/process/process_processlist.php:961 Stack trace: #0 /var/www/vhosts/MY_SERVER/httpdocs/statistic/Modules/process/process_processlist.php(961): DateTimeZone->__construct('') 
#1 [internal function]: Process_ProcessList->getstartday(1528373449, Object(Process)) 
#2 /var/www/vhosts/MY_SERVER/httpdocs/statistic/Modules/process/process_model.php(62): call_user_func_array(Array, Array) 
#3 /var/www/vhosts/MY_SERVER/httpdocs/statistic/Modules/feed/engine/VirtualFeed.php(81): Process->__call('process__getsta...', Array) 
#4 /var/www/vhosts/MY_SERVER/httpdocs/statistic/Modules/feed/engine/VirtualFeed.php(81): Process->process__getstartday(1528373449) 
#5 /var/www/vhosts/MY_SERVER/httpdocs/statistic/Modules/feed/feed_model.php(351): VirtualFeed->lastvalue(' in /var/www/vhosts/MY_SERVER/httpdocs/statistic/Modules/process/process_processlist.php on line 961
```

**Comment by Rai-Rai** [comment]
Hi,
I've posted the issue there [Link](https://community.openenergymonitor.org/t/gaug-and-feedvalue-not-showing-after-update-9-8-3-9-8-30/7598/1)

But I think the problem is caused by the exception in `process_processlist.php`. Only the error message is send to the dashboard instead of valid data to display whcih leads to the console.error
